# -*- coding: utf-8 -*-
"""The 48 commands of Jesus used by all three volumes, one per week.

Names and references match the store (public/assets/app.*.js). Scripture is the King James Version,
taken from the NewStart Discipleship list (Commands.pdf); six long passages are shortened with an
ellipsis, keeping the King James words. KJV is public domain in the United States.
"""

COMMANDS = [
 dict(n=1, name="Repent", ref="Matthew 4:17",
      kjv="From that time Jesus began to preach, and to say, Repent: for the kingdom of heaven is at hand."),
 dict(n=2, name="Follow Me", ref="Matthew 4:19",
      kjv="And he saith unto them, Follow me, and I will make you fishers of men."),
 dict(n=3, name="Rejoice", ref="Matthew 5:12",
      kjv="Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you."),
 dict(n=4, name="Let Your Light Shine", ref="Matthew 5:16",
      kjv="Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."),
 dict(n=5, name="Honor God’s Law", ref="Matthew 5:17-19",
      kjv="Think not that I am come to destroy the law, or the prophets: I am not come to destroy, but to fulfil. … whosoever shall do and teach them, the same shall be called great in the kingdom of heaven."),
 dict(n=6, name="Be Reconciled", ref="Matthew 5:24-25",
      kjv="Leave there thy gift before the altar, and go thy way; first be reconciled to thy brother, and then come and offer thy gift. Agree with thine adversary quickly, whiles thou art in the way with him; lest at any time the adversary deliver thee to the judge, and the judge deliver thee to the officer, and thou be cast into prison."),
 dict(n=7, name="Do Not Lust", ref="Matthew 5:28-30",
      kjv="But I say unto you, That whosoever looketh on a woman to lust after her hath committed adultery with her already in his heart. And if thy right eye offend thee, pluck it out, and cast it from thee …"),
 dict(n=8, name="Keep Your Word", ref="Matthew 5:37",
      kjv="But let your communication be, Yea, yea; Nay, nay: for whatsoever is more than these cometh of evil."),
 dict(n=9, name="Go the Second Mile", ref="Matthew 5:38-42",
      kjv="But I say unto you, That ye resist not evil: but whosoever shall smite thee on thy right cheek, turn to him the other also. … And whosoever shall compel thee to go a mile, go with him twain."),
 dict(n=10, name="Love Your Enemies", ref="Matthew 5:44",
      kjv="But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;"),
 dict(n=11, name="Be Perfect", ref="Matthew 5:48",
      kjv="Be ye therefore perfect, even as your Father which is in heaven is perfect."),
 dict(n=12, name="Practice Secret Disciplines", ref="Matthew 6:3-4, 6, 17-18",
      kjv="But when thou doest alms, let not thy left hand know what thy right hand doeth … But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret … But thou, when thou fastest, anoint thine head, and wash thy face … and thy Father, which seeth in secret, shall reward thee openly."),
 dict(n=13, name="Lay Up Treasures in Heaven", ref="Matthew 6:19-21",
      kjv="Lay not up for yourselves treasures upon earth, where moth and rust doth corrupt, and where thieves break through and steal: But lay up for yourselves treasures in heaven, where neither moth nor rust doth corrupt, and where thieves do not break through nor steal: For where your treasure is, there will your heart be also."),
 dict(n=14, name="Seek God’s Kingdom", ref="Matthew 6:33",
      kjv="But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."),
 dict(n=15, name="Judge Not", ref="Matthew 7:1-2",
      kjv="Judge not, that ye be not judged. For with what judgment ye judge, ye shall be judged: and with what measure ye mete, it shall be measured to you again."),
 dict(n=16, name="Do Not Throw Pearls to Pigs", ref="Matthew 7:6",
      kjv="Give not that which is holy unto the dogs, neither cast ye your pearls before swine, lest they trample them under their feet, and turn again and rend you."),
 dict(n=17, name="Ask, Seek, Knock", ref="Matthew 7:7-8",
      kjv="Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you: For every one that asketh receiveth; and he that seeketh findeth; and to him that knocketh it shall be opened."),
 dict(n=18, name="Do Unto Others", ref="Matthew 7:12",
      kjv="Therefore all things whatsoever ye would that men should do to you, do ye even so to them: for this is the law and the prophets."),
 dict(n=19, name="Choose the Narrow Way", ref="Matthew 7:13-14",
      kjv="Enter ye in at the strait gate: for wide is the gate, and broad is the way, that leadeth to destruction, and many there be which go in thereat: Because strait is the gate, and narrow is the way, which leadeth unto life, and few there be that find it."),
 dict(n=20, name="Beware of False Prophets", ref="Matthew 7:15",
      kjv="Beware of false prophets, which come to you in sheep's clothing, but inwardly they are ravening wolves."),
 dict(n=21, name="Pray for Laborers", ref="Matthew 9:38",
      kjv="Pray ye therefore the Lord of the harvest, that he will send forth labourers into his harvest."),
 dict(n=22, name="Be Wise as Serpents", ref="Matthew 10:16",
      kjv="Behold, I send you forth as sheep in the midst of wolves: be ye therefore wise as serpents, and harmless as doves."),
 dict(n=23, name="Fear Not", ref="Matthew 10:28",
      kjv="And fear not them which kill the body, but are not able to kill the soul: but rather fear him which is able to destroy both soul and body in hell."),
 dict(n=24, name="Hear God’s Voice", ref="Matthew 11:15",
      kjv="He that hath ears to hear, let him hear."),
 dict(n=25, name="Take My Yoke", ref="Matthew 11:29",
      kjv="Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls."),
 dict(n=26, name="Honor Your Parents", ref="Matthew 15:4",
      kjv="For God commanded, saying, Honour thy father and mother: and, He that curseth father or mother, let him die the death."),
 dict(n=27, name="Beware of Leaven", ref="Matthew 16:6",
      kjv="Then Jesus said unto them, Take heed and beware of the leaven of the Pharisees and of the Sadducees."),
 dict(n=28, name="Deny Yourself", ref="Matthew 16:24",
      kjv="Then said Jesus unto his disciples, If any man will come after me, let him deny himself, and take up his cross, and follow me."),
 dict(n=29, name="Do Not Despise Little Ones", ref="Matthew 18:10",
      kjv="Take heed that ye despise not one of these little ones; for I say unto you, That in heaven their angels do always behold the face of my Father which is in heaven."),
 dict(n=30, name="Go to Offenders", ref="Matthew 18:15",
      kjv="Moreover if thy brother shall trespass against thee, go and tell him his fault between thee and him alone: if he shall hear thee, thou hast gained thy brother."),
 dict(n=31, name="Beware of Covetousness", ref="Luke 12:15",
      kjv="And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in the abundance of the things which he possesseth."),
 dict(n=32, name="Forgive Offenders", ref="Matthew 18:21-22",
      kjv="Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven."),
 dict(n=33, name="Honor Marriage", ref="Matthew 19:6",
      kjv="Wherefore they are no more twain, but one flesh. What therefore God hath joined together, let not man put asunder."),
 dict(n=34, name="Be a Servant", ref="Matthew 20:26-27",
      kjv="But it shall not be so among you: but whosoever will be great among you, let him be your minister; And whosoever will be chief among you, let him be your servant:"),
 dict(n=35, name="Be a House of Prayer", ref="Matthew 21:13",
      kjv="And said unto them, It is written, My house shall be called the house of prayer; but ye have made it a den of thieves."),
 dict(n=36, name="Ask in Faith", ref="Matthew 21:21-22",
      kjv="Jesus answered and said unto them, Verily I say unto you, If ye have faith, and doubt not, ye shall not only do this which is done to the fig tree, but also if ye shall say unto this mountain, Be thou removed, and be thou cast into the sea; it shall be done. And all things, whatsoever ye shall ask in prayer, believing, ye shall receive."),
 dict(n=37, name="Bring in the Poor", ref="Luke 14:12-14",
      kjv="When thou makest a dinner or a supper, call not thy friends, nor thy brethren, neither thy kinsmen, nor thy rich neighbours … But when thou makest a feast, call the poor, the maimed, the lame, the blind: And thou shalt be blessed; for they cannot recompense thee …"),
 dict(n=38, name="Render to Caesar", ref="Matthew 22:19-21",
      kjv="Shew me the tribute money. And they brought unto him a penny. And he saith unto them, Whose is this image and superscription? They say unto him, Caesar's. Then saith he unto them, Render therefore unto Caesar the things which are Caesar's; and unto God the things that are God's."),
 dict(n=39, name="Love the Lord", ref="Matthew 22:37",
      kjv="Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind."),
 dict(n=40, name="Love Your Neighbor", ref="Matthew 22:39",
      kjv="And the second is like unto it, Thou shalt love thy neighbour as thyself."),
 dict(n=41, name="Await My Return", ref="Matthew 24:42-44",
      kjv="Watch therefore: for ye know not what hour your Lord doth come. But know this, that if the goodman of the house had known in what watch the thief would come, he would have watched, and would not have suffered his house to be broken up. Therefore be ye also ready: for in such an hour as ye think not the Son of man cometh."),
 dict(n=42, name="Celebrate the Lord’s Supper", ref="Matthew 26:26-27",
      kjv="And as they were eating, Jesus took bread, and blessed it, and brake it, and gave it to the disciples, and said, Take, eat; this is my body. And he took the cup, and gave thanks, and gave it to them, saying, Drink ye all of it;"),
 dict(n=43, name="Watch and Pray", ref="Matthew 26:41",
      kjv="Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak."),
 dict(n=44, name="Feed My Sheep", ref="John 21:15-16",
      kjv="Simon, son of Jonas, lovest thou me more than these? He saith unto him, Yea, Lord; thou knowest that I love thee. He saith unto him, Feed my lambs. … He saith unto him, Feed my sheep."),
 dict(n=45, name="Baptize My Disciples", ref="Matthew 28:19",
      kjv="Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:"),
 dict(n=46, name="Teach Them to Obey My Commands", ref="Matthew 28:20",
      kjv="Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."),
 dict(n=47, name="Receive God’s Power", ref="Luke 24:49",
      kjv="And, behold, I send the promise of my Father upon you: but tarry ye in the city of Jerusalem, until ye be endued with power from on high."),
 dict(n=48, name="Make Disciples", ref="Matthew 28:19-20",
      kjv="Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen. winging it"),
]
assert [c["n"] for c in COMMANDS] == list(range(1, 49))
